routes/web.php
<?php
namespace App\Http\Controllers;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {

    if (isset(Auth::user()->id)) {
        return redirect()->route('home');
    } else {
        return view('welcome');
    }
})->name('index');



Route::get('home', [HomeController::class, 'home'])->name('home');
Route::post('login', [UserController::class, 'login'])->name('login');
Route::get('logout', [UserController::class, 'logout'])->name('logout');

Route::get('categorias', [CategoriaPostController::class, 'index'])->name('categorias');
Route::get('posts', [PostController::class, 'index'])->name('posts');
Route::get('createPost', [PostController::class, 'createPost'])->name('createPost');
Route::get('editarPost/{slug}', [PostController::class, 'editPost'])->name('editPost');
Route::post('storePost', [PostController::class, 'store'])->name('storePost');
Route::post('updatePost', [PostController::class, 'update'])->name('updatePost');

app/Http/Livewire/CategoriasComponent.php
<?php

namespace App\Http\Livewire;

use App\Models\CategoriaPost;
use Livewire\Component;

use Jantinnerezo\LivewireAlert\LivewireAlert;

class CategoriasComponent extends Component
{

    use LivewireAlert;

    public $view = "list";
    public $categoria, $idEditando;

    public function render()
    {
        $categorias = CategoriaPost::withCount('posts')->get();

        return view('livewire.categorias-component', compact('categorias'));
    }

    public function create()
    {
        $this->view = "create";
    }

    public function edit($idCategoria)
    {
        $categoria = CategoriaPost::find($idCategoria);
        $this->categoria = $categoria->categoria;
        $this->idEditando = $categoria->id;
        $this->view = "edit";
    }

    public function update()
    {
        $categoria = CategoriaPost::find($this->idEditando);
        $categoria->categoria = $this->categoria;
        $categoria->save();

        $this->view = "list";
        $this->alert('success', 'Categoria editada con exito!');
    }

    public function save()
    {
        $create = CategoriaPost::create([
            'categoria' => $this->categoria
        ]);

        $this->categoria = "";
        $this->view = "list";
        $this->alert('success', 'Categoria creada con exito!');
    }

    public function eliminar($idCategoria)
    {
        $categoria = CategoriaPost::find($idCategoria);

        $categoria->delete();
        $this->alert('success', 'Categoria eliminada con exito!');
    }

    public function procesarEliminare($cat)
    {
        $cat->delete();

    }
}

resources/views/livewire/modulos/categorias/create.blade.php
<div class="container-fluid">
    <div class="row my-3">
        <div class="col-md-10  offset-md-1">
            <form action="#">
                <div class="card no-b  no-r">
                    <div class="card-body">
                        <h5 class="card-title">Crear Categoriaa</h5>
                        <div class="form-row">
                            <div class="col-md-12">
                                <div class="form-group m-0">
                                    <label for="name" class="col-form-label s-12">Categoria</label>
                                    <input id="name" placeholder="Categoria" class="form-control r-0 light s-12 "
                                        wire:model='categoria' type="text">
                                </div>

                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="card-body">
                        <button type="button" wire:click='save()' class="btn btn-primary w-100"><i
                                class="icon-save mr-2"></i>Guardar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/livewire/modulos/categorias/edit.blade.php
<div class="container-fluid">
    <div class="row my-3">
        <div class="col-md-10  offset-md-1">
            <form action="#">
                <div class="card no-b  no-r">
                    <div class="card-body">
                        <h5 class="card-title">Editar Categoriaa</h5>
                        <div class="form-row">
                            <div class="col-md-12">
                                <div class="form-group m-0">
                                    <label for="name" class="col-form-label s-12">Categoria</label>
                                    <input id="name" placeholder="Categoria" class="form-control r-0 light s-12 "
                                        wire:model='categoria' type="text">
                                </div>

                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="card-body">
                        <button type="button" wire:click='update()' class="btn btn-primary w-100"><i
                                class="icon-save mr-2"></i>Guardar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/livewire/modulos/categorias/list.blade.php
<div class="row my-3 ml-3 mr-3">
    <div class="col-md-12">
        <div class="card r-0 shadow">
            <div class="table-responsive">
                <form>
                    <table class="table table-striped table-hover r-0">
                        <thead>
                            <tr class="no-b">
                                <th>Id</th>
                                <th>Categoria</th>
                                <th>Posts</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            @forelse ($categorias as $categoria)
                            <tr>
                                <td>{{ $categoria->id }}</td>
                                <td>{{ $categoria->categoria }}</td>
                                <td>{{ $categoria->posts_count }}</td>
                                <td>
                                    <i class="s-24 icon-pencil-square text-success" wire:click='edit({{$categoria->id}})' style="font-size: 30px"></i>
                                    <i class="s-24 icon-trash text-danger" wire:click='eliminar({{$categoria->id}})' style="font-size: 30px"></i>
                                </td>
                            </tr>
                            @empty
                            <tr class="text-center">
                                <td colspan="3" class="py-3 italic">No hay información</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>


</div>